export const userData = [
  {
    userName: "Ginédine",
    genders: [
      "Romantique",
      "XXX",
      "Documentaire",
      "Humour",
      "Thriller",
      "Faudrait faire quelque chose là",
    ],
    critic: 59,
    note: 16,
    masterpiece: 17,
    watchlist: 4,
  },
  {
    userName: "Robert",
    genders: ["Science fiction", "Action", "Drame"],
    critic: 27,
    note: 54,
    masterpiece: 12,
    watchlist: 5,
  },
  {
    userName: "Robert",
    genders: ["Science fiction", "Action", "Drame"],
    critic: 27,
    note: 54,
    masterpiece: 12,
    watchlist: 5,
  },
  {
    userName: "Robert",
    genders: ["Science fiction", "Action", "Drame"],
    critic: 27,
    note: 54,
    masterpiece: 12,
    watchlist: 5,
  },
  {
    userName: "Robert",
    genders: ["Science fiction", "Action", "Drame"],
    critic: 27,
    note: 54,
    masterpiece: 12,
    watchlist: 5,
  },
];
